<a href="https://colab.research.google.com/github/Akanksha092004/data-analyst-task1/blob/main/task1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [19]:
from datetime import datetime
import numpy as np
import pandas as pd

In [20]:
import warnings
warnings.filterwarnings('ignore')

In [21]:
df = pd.read_csv("/content/sample_data/intership/netflix_dataset.csv")

before cleaning

In [22]:
print("Before Cleaning:")
print(df.shape)
print(df.isnull().sum())

Before Cleaning:
(300, 7)
title            0
type             0
country         59
date_added      68
release_year    57
rating          57
genre           60
dtype: int64

1. Remove missing values

In [23]:
df = df.dropna()

 2. Remove duplicates

In [24]:
df = df.drop_duplicates()

3. Clean text columns

In [29]:
for col in df.select_dtypes(include='object').columns:
    df[col] = df[col].str.lower().str.strip()

4. Rename columns

In [32]:
df.columns = df.columns.str.lower().str.replace(" ", "_")

In [27]:
df.head(5)

       title     type country     date_added  release_year rating     genre
0   series e    movie     usa     2021-02-15        2019.0      r    action
5    movie b  tv show      uk     2021-02-15        2021.0      r    comedy
12    show c    movie      uk  15 march 2022        2019.0     pg    action
16    film d  tv show   india     2021-02-15        2021.0      r  thriller
17    show c    movie   india  15 march 2022        2020.0     pg     drama

5. Convert date column

In [30]:
df['date_added'] = pd.to_datetime(df['date_added'], errors='coerce')

In [31]:
df.head(5)

       title     type country date_added  release_year rating     genre
0   series e    movie     usa 2021-02-15        2019.0      r    action
5    movie b  tv show      uk 2021-02-15        2021.0      r    comedy
12    show c    movie      uk        NaT        2019.0     pg    action
16    film d  tv show   india 2021-02-15        2021.0      r  thriller
17    show c    movie   india        NaT        2020.0     pg     drama

In [33]:
print(df.dtypes)

title                   object
type                    object
country                 object
date_added      datetime64[ns]
release_year           float64
rating                  object
genre                   object
dtype: object

In [34]:
df['release_year'] = df['release_year'].astype(int)

 After cleaning

In [35]:
print("\nAfter Cleaning:")
print(df.shape)
print(df.isnull().sum())

After Cleaning:
(100, 7)
title            0
type             0
country          0
date_added      73
release_year     0
rating           0
genre            0
dtype: int64

In [38]:
df.to_csv("cleaned_netflix_dataset.csv", index=False)

In [36]:
print(df)

        title     type country date_added  release_year rating     genre
0    series e    movie     usa 2021-02-15          2019      r    action
5     movie b  tv show      uk 2021-02-15          2021      r    comedy
12     show c    movie      uk        NaT          2019     pg    action
16     film d  tv show   india 2021-02-15          2021      r  thriller
17     show c    movie   india        NaT          2020     pg     drama
..        ...      ...     ...        ...           ...    ...       ...
292  series e  tv show      uk        NaT          2019      r     drama
293   movie a  tv show   india 2021-02-15          2020  tv-ma     drama
295  series e  tv show      uk        NaT          2019      r    comedy
296    film d  tv show      uk 2021-02-15          2021     pg    action
298    film d    movie   india 2021-02-15          2021      r    comedy

[100 rows x 7 columns]